repos:
  - repo: local
    hooks:
      - id: run-pytest
        name: Run Pytest before push
        entry: bash -c "cd $(git rev-parse --show-toplevel) && pytest"
        language: system
        stages: [pre-push]
