repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout

  - repo: local
    hooks:
      - id: run-pytest
        name: Run Pytest before push
        entry: bash -c "cd $(git rev-parse --show-toplevel) && pytest"
        language: system
        stages: [pre-push]
